### ISSUE TITLE
French ID

### ISSUE THREAD

**Issue by bojanpog** [tetrahydra/SolidusMRZ#5]
Hello!

Just tried to decode MRZ of french ID and it don't work. I've found that French uses some different MRZ format: https://en.wikipedia.org/wiki/National_identity_card_(France) .. 

At char 6 should begin document number, but card holders name is written.

How to solve this?

**Comment by tetrahydra** [comment]
Hello,

Can you send me a private mail of the MRZ? To see if I can make a work around for it. TQ

**Comment by bojanpog** [comment]
Hello!

IDFRAMEYER<<<<<<<<<<<<<<<<<<<<675034
1305675007505MALO<<ALAIN<<J1212031M1


BR, Bojan


Ed je 13.7.2018 ob 16:59 napisal:

**Comment by bojanpog** [comment]
Just sent. Tnx

**Comment by tetrahydra** [comment]
I'm checking the MRZ for the French ID card and indeed no proper output came. 

Is there any convention for European ID card that I can refer to, or each country has its own convention/standard?

**Comment by bojanpog** [comment]
As far I can tell is that all EU ID cards are working OK with current code, except:
- German ID cards don't have gender written (empty field - < )
- German country abbr is not 3 char long, but just 1 ( D )
- France ID cards have own format. 

I am preparing a basic pull request for France you can then improve?

**Comment by tetrahydra** [comment]
I have updated the code for the card for France. As I haven't seen any other from EU countries, it only works for French ID card. However, it can be extended to include other EU countries easily.

Please have a try and let me know if it works. Thank you.

**Comment by tetrahydra** [comment]
I have merged your pull request number 7.

But i have to remove the EXPIRY because the information is not explicitly derived from the MRZ. The purpose for this library is to read and decode only explicit information.

**Comment by tetrahydra** [comment]
I think the request works now and i am closing this issue.
